// <auto-generated />
using System;
using AstronomyViewer.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AstronomyViewer.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401080528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AstronomyViewer.API.Models.CelestialObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Declination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RightAscension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CelestialObjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 4, 1, 8, 5, 26, 989, DateTimeKind.Utc).AddTicks(9258),
                            Declination = "N/A",
                            Description = "The star at the center of the Solar System.",
                            ImageUrl = "https://example.com/sun.jpg",
                            Name = "Sun",
                            RightAscension = "N/A",
                            Type = "Star"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 4, 1, 8, 5, 26, 989, DateTimeKind.Utc).AddTicks(9291),
                            Declination = "+12d 34m 56s",
                            Description = "The fourth planet from the Sun and the second-smallest planet in the Solar System.",
                            ImageUrl = "https://example.com/mars.jpg",
                            Name = "Mars",
                            RightAscension = "12h 34m 56s",
                            Type = "Planet"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 4, 1, 8, 5, 26, 989, DateTimeKind.Utc).AddTicks(9305),
                            Declination = "+41d 16m 09s",
                            Description = "A barred spiral galaxy approximately 2.5 million light-years from Earth.",
                            ImageUrl = "https://example.com/andromeda.jpg",
                            Name = "Andromeda Galaxy",
                            RightAscension = "00h 42m 44s",
                            Type = "Galaxy"
                        });
                });

            modelBuilder.Entity("AstronomyViewer.API.Models.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CelestialObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CelestialObjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("AstronomyViewer.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AstronomyViewer.API.Models.Favorite", b =>
                {
                    b.HasOne("AstronomyViewer.API.Models.CelestialObject", "CelestialObject")
                        .WithMany()
                        .HasForeignKey("CelestialObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstronomyViewer.API.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CelestialObject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstronomyViewer.API.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
